unstable_features = true
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
empty_item_single_line = true
fn_params_layout = "Tall"
fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
hard_tabs = true
match_block_trailing_comma = true
normalize_comments = true
match_arm_blocks = true
normalize_doc_attributes = true
hex_literal_case = "Upper"
group_imports = "StdExternalCrate"
remove_nested_parens = true
reorder_impl_items = true
spaces_around_ranges = true
combine_control_expr = false
trailing_comma = "Never"
trailing_semicolon = true